# Generated by Django 5.2.4 on 2025-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_alter_usersignup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
